//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnetSenderCore {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnetSenderCore.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;STATE&quot;:&quot;VALUE_BLINDS&quot;,&quot;VALUE&quot;:{value},&quot;NUMBER&quot;:{channel}}]}
        ///
        /// ähnelt.
        /// </summary>
        internal static string BlindsValueSetMessage {
            get {
                return ResourceManager.GetString("BlindsValueSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;GET_CHANNEL_INFO_ALL_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;}
        ///
        /// ähnelt.
        /// </summary>
        internal static string GetChannelInfoMessage {
            get {
                return ResourceManager.GetString("GetChannelInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;PROJECT_LIST_GET&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        /// ähnelt.
        /// </summary>
        internal static string GetProjectList {
            get {
                return ResourceManager.GetString("GetProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;VERSION_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        /// ähnelt.
        /// </summary>
        internal static string GetVersionMessage {
            get {
                return ResourceManager.GetString("GetVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:16,&quot;STATE&quot;:&quot;ON&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///   ähnelt.
        /// </summary>
        internal static string SchrankAn {
            get {
                return ResourceManager.GetString("SchrankAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:16,&quot;STATE&quot;:&quot;OFF&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///   ähnelt.
        /// </summary>
        internal static string SchrankAus {
            get {
                return ResourceManager.GetString("SchrankAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SIGN_IN_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;ITEMS&quot;:[{channel}],&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        /// ähnelt.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SIGN_OUT_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;ITEMS&quot;:[{channel}],&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        /// ähnelt.
        /// </summary>
        internal static string SignOff {
            get {
                return ResourceManager.GetString("SignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:{channel},&quot;STATE&quot;:&quot;{state}&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///   ähnelt.
        /// </summary>
        internal static string ValueSetMessageTemplate {
            get {
                return ResourceManager.GetString("ValueSetMessageTemplate", resourceCulture);
            }
        }
    }
}
