//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSocketClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSocketClient.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;STATE&quot;:&quot;VALUE_BLINDS&quot;,&quot;VALUE&quot;:{value},&quot;NUMBER&quot;:{channel}}]}
        ///
        ///.
        /// </summary>
        internal static string BlindsValueSetMessage {
            get {
                return ResourceManager.GetString("BlindsValueSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;GET_CHANNEL_INFO_ALL_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;}
        ///
        ///.
        /// </summary>
        internal static string GetChannelInfoMessage {
            get {
                return ResourceManager.GetString("GetChannelInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;VERSION_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        ///.
        /// </summary>
        internal static string GetVersionMessage {
            get {
                return ResourceManager.GetString("GetVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:16,&quot;STATE&quot;:&quot;ON&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///  .
        /// </summary>
        internal static string SchrankAn {
            get {
                return ResourceManager.GetString("SchrankAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:16,&quot;STATE&quot;:&quot;OFF&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///  .
        /// </summary>
        internal static string SchrankAus {
            get {
                return ResourceManager.GetString("SchrankAus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SIGN_IN_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;ITEMS&quot;:[16],&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        ///.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SIGN_OUT_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;ITEMS&quot;:[16],&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}
        ///
        ///.
        /// </summary>
        internal static string SignOff {
            get {
                return ResourceManager.GetString("SignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;ITEM_VALUE_SET&quot;,&quot;TIMESTAMP&quot;:&quot;1421948266&quot;,&quot;VALUES&quot;:[{&quot;NUMBER&quot;:{channel},&quot;STATE&quot;:&quot;{state}&quot;}],&quot;PROTOCOL&quot;:&quot;0.03&quot;}
        ///
        ///  .
        /// </summary>
        internal static string ValueSetMessageTemplate {
            get {
                return ResourceManager.GetString("ValueSetMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;CMD&quot;:&quot;VERSION_REQ&quot;,&quot;PROTOCOL&quot;:&quot;0.03&quot;,&quot;TIMESTAMP&quot;:&quot;1421948265&quot;}\r\n\r\n.
        /// </summary>
        internal static string VersionMessage {
            get {
                return ResourceManager.GetString("VersionMessage", resourceCulture);
            }
        }
    }
}
